### PR TITLE
Potion Store updated to Rails 2.3.10 and latest async Google Analytics

### PR DESCRIPTION
**Pull request by ghost**
Andy - thanks for all the hard work on the project, I'd like to contribute back here a bit more.

I've done the minor tweaks necessary to migrate the store to rails 2.3.10 and I'll likely be pushing it into Rails 3 in the next few weeks. Not everybody is ready to go to Rails 3, however, and having a stable and up to date 2.3 line is important - for security if no other reason.

I've also updated the GA code to use their async handling rather than the super-old urchin stuff. It speeds page loads a bit and is more future-proof.

### CODE REVIEW

**Comment by andypotion** [comment]
Thanks for all the changes. I'll merge it when I get some free time after releasing some apps I'm working on.

**Comment by tcurdt** [comment]
any news here? would also like to see this merged
...and then it would be worth to look into rails 3.x

**Comment by hemancuso** [comment]
I'm happy to do a rails 3 update too.

Andy - if you can merge this in, I'll start things on their way to rails 3.

**Comment by andypotion** [comment]
I already merged this into my private branch, but I'm afraid that it'll take some work to pick out the changes that I want to contribute back to the public branch. I'll have to find some time one of these days...

**Comment by expandrive** [comment]
Couldn't we just merge it directly into the public branch and then you rebase your private branch against the public branch?

**Comment by andypotion** [comment]
The pull request is merged into the master branch. I also released the stuff I hadn't released yet into a new "develop" branch.

**Pull request merged**
